In [568]:
import numpy as np
import pandas as pd
import ast

In [569]:
movies = pd.read_csv('tmdb_5000_movies.csv')
credits = pd.read_csv('tmdb_5000_credits.csv')

In [570]:
movies.head(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800

In [571]:
credits.head(1)

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [572]:
movies = movies.merge(credits,on='title')

In [573]:
movies.head(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [574]:
movies = movies[['movie_id','title','overview','genres','keywords','cast','crew']]

In [575]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4809 entries, 0 to 4808
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   movie_id  4809 non-null   int64
 1   title     4809 non-null   object
 2   overview  4806 non-null   object
 3   genres    4809 non-null   object
 4   keywords  4809 non-null   object
 5   cast      4809 non-null   object
 6   crew      4809 non-null   object
dtypes: int64(1), object(6)
memory usage: 300.6+ KB

In [576]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bondâ€™s past sends him o...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [577]:
#data cleaning section
movies.isnull().sum()

movie_id    0
title       0
overview    3
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [578]:
movies.dropna(inplace=True)

In [579]:
movies.duplicated().sum()

0

In [580]:
#segregating the wanted data

movies.iloc[0].genres

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [581]:
def convert(obj):
    L =[]
    for i in ast.literal_eval(obj):
        L.append(i['name'])
    return L

In [582]:
movies['genres'] = movies['genres'].apply(convert)

In [583]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bondâ€™s past sends him o...,"[Action, Adventure, Crime]","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [584]:
movies['keywords'] = movies['keywords'].apply(convert)

In [585]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bondâ€™s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [586]:
def convert3(obj):
    L =[]
    counter = 0
    for i in ast.literal_eval(obj):
        if counter != 3:
            L.append(i['name'])
            counter+=1
        else:
            break
    
    return L

In [587]:
movies['cast'] = movies['cast'].apply(convert3)

In [588]:
def fetch_director(obj):
    L =[]
    for i in ast.literal_eval(obj):
        if i['job'] == 'Director':
            L.append(i['name'])
            break
    return L

In [589]:
movies['crew'] = movies['crew'].apply(fetch_director)

In [592]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,206647,Spectre,A cryptic message from Bondâ€™s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, LÃ©a Seydoux]",[Sam Mendes]
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]

In [593]:


movies['overview'][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.'

In [594]:
movies['overview'] = movies['overview'].apply(lambda x:x.split())

In [595]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,206647,Spectre,"[A, cryptic, message, from, Bondâ€™s, past, send...","[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, LÃ©a Seydoux]",[Sam Mendes]
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]

In [606]:
movies['genres'] = movies['genres'].apply(lambda x:[i.replace(" ","") for i in x])
movies['keywords'] = movies['keywords'].apply(lambda x:[i.replace(" ","") for i in x])
movies['cast'] = movies['cast'].apply(lambda x:[i.replace(" ","") for i in x])
movies['crew'] = movies['crew'].apply(lambda x:[i.replace(" ","") for i in x])

In [608]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron],"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski],"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bondâ€™s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LÃ©aSeydoux]",[SamMendes],"[A, cryptic, message, from, Bondâ€™s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan],"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton],"[John, Carter, is, a, war-weary,, former, mili..."

In [609]:
movies['tags'] = movies['overview'] + movies['genres'] + movies['keywords'] + movies['cast'] + movies['crew']

In [610]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron],"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski],"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bondâ€™s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LÃ©aSeydoux]",[SamMendes],"[A, cryptic, message, from, Bondâ€™s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan],"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton],"[John, Carter, is, a, war-weary,, former, mili..."

In [618]:
new_df = movies[['movie_id','title','tags']]

In [619]:
new_df['tags'] = new_df['tags'].apply(lambda x:" ".join(x))

<ipython-input-619-ad44e9ca1347>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x:" ".join(x))

In [620]:
new_df['tags'][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. Action Adventure Fantasy ScienceFiction cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d SamWorthington ZoeSaldana SigourneyWeaver JamesCameron'

In [621]:
new_df['tags'] = new_df['tags'].apply(lambda x:x.lower())

<ipython-input-621-8b60b591a07f>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x:x.lower())

In [622]:
new_df.head()

,movie_id,title,tags
0,19995,Avatar,"in the 22nd century, a paraplegic marine is di..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believed to be dead, ha..."
2,206647,Spectre,a cryptic message from bondâ€™s past sends him o...
3,49026,The Dark Knight Rises,following the death of district attorney harve...
4,49529,John Carter,"john carter is a war-weary, former military ca..."

In [719]:
#Steming of words (Bag of words)

import nltk

from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [720]:
def stem(text):
    y = []
    
    for i in text.split():
        y.append(ps.stem(i))
    return " ".join(y)

In [722]:
new_df['tags'] = new_df['tags'].apply(stem)

<ipython-input-722-be18a4346d89>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(stem)

In [723]:
# stem('loving')

'love'

In [724]:
new_df['tags'][0]

'in the 22nd century, a parapleg marin is dispatch to the moon pandora on a uniqu mission, but becom torn between follow order and protect an alien civilization. action adventur fantasi sciencefict cultureclash futur spacewar spacecoloni societi spacetravel futurist romanc space alien tribe alienplanet cgi marin soldier battl loveaffair antiwar powerrel mindandsoul 3d samworthington zoesaldana sigourneyweav jamescameron'

In [725]:
new_df['tags'][1]

"captain barbossa, long believ to be dead, ha come back to life and is head to the edg of the earth with will turner and elizabeth swann. but noth is quit as it seems. adventur fantasi action ocean drugabu exoticisland eastindiatradingcompani loveofone'slif traitor shipwreck strongwoman ship allianc calypso afterlif fighter pirat swashbuckl aftercreditsst johnnydepp orlandobloom keiraknightley goreverbinski"

In [726]:
#Text Vectorization

from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000,stop_words='english')

In [727]:
vectors = cv.fit_transform(new_df['tags']).toarray()

In [728]:
vectors

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [731]:
vectors[0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [732]:
cv.get_feature_names()

['000',
 '007',
 '10',
 '100',
 '11',
 '12',
 '13',
 '14',
 '15',
 '16',
 '17',
 '17th',
 '18',
 '18th',
 '18thcenturi',
 '19',
 '1910',
 '1920',
 '1930',
 '1940',
 '1944',
 '1950',
 '1950s',
 '1960',
 '1960s',
 '1970',
 '1970s',
 '1971',
 '1974',
 '1976',
 '1980',
 '1985',
 '1990',
 '1999',
 '19th',
 '19thcenturi',
 '20',
 '200',
 '2003',
 '2009',
 '20th',
 '21st',
 '23',
 '24',
 '25',
 '30',
 '300',
 '3d',
 '40',
 '50',
 '500',
 '60',
 '70',
 '80',
 'aaron',
 'aaroneckhart',
 'abandon',
 'abduct',
 'abigailbreslin',
 'abil',
 'abl',
 'aboard',
 'abov',
 'abu',
 'academ',
 'academi',
 'accept',
 'access',
 'accid',
 'accident',
 'acclaim',
 'accompani',
 'accomplish',
 'account',
 'accu',
 'ace',
 'achiev',
 'acquaint',
 'act',
 'action',
 'actionhero',
 'activ',
 'activist',
 'activities',
 'actor',
 'actress',
 'actual',
 'ad',
 'adam',
 'adamsandl',
 'adamshankman',
 'adapt',
 'add',
 'addict',
 'adjust',
 'admir',
 'admit',
 'adolesc',
 'adopt',
 'ador',
 'adrienbrodi',
 'adult',
 'adultanim',
 'adulteri',
 'adulthood',
 'advanc',
 'adventur',
 'adventure',
 'adventures',
 'adverti',
 'advi',
 'advic',
 'affair',
 'affect',
 'afghanistan',
 'africa',
 'african',
 'africanamerican',
 'aftercreditsst',
 'afterlif',
 'aftermath',
 'ag',
 'age',
 'agediff',
 'agenc',
 'agency',
 'agenda',
 'agent',
 'agents',
 'aggress',
 'ago',
 'agr',
 'ahead',
 'aid',
 'aidanquinn',
 'ail',
 'aim',
 'air',
 'airplan',
 'airplanecrash',
 'airport',
 'aka',
 'al',
 'alabama',
 'alan',
 'alaska',
 'albert',
 'alcatraz',
 'alcohol',
 'alecbaldwin',
 'alex',
 'alexkendrick',
 'alfredhitchcock',
 'alfredmolina',
 'ali',
 'alic',
 'alice',
 'alien',
 'alieninva',
 'alienlife',
 'alienplanet',
 'aliens',
 'alik',
 'aliv',
 'alive',
 'allen',
 'alli',
 'allianc',
 'allow',
 'alon',
 'alongsid',
 'alpacino',
 'alpha',
 'alreadi',
 'alter',
 'altern',
 'alway',
 'alyssa',
 'alzheimer',
 'amanda',
 'amandapeet',
 'amandaseyfri',
 'amateur',
 'amaz',
 'amazon',
 'ambassador',
 'ambit',
 'ambiti',
 'ambul',
 'ambush',
 'america',
 'american',
 'americanabroad',
 'americancivilwar',
 'americanfootb',
 'americanfootballplay',
 'amid',
 'amidst',
 'amnesia',
 'amp',
 'amsterdam',
 'amu',
 'amusementpark',
 'amy',
 'amyadam',
 'amysmart',
 'ana',
 'anakin',
 'analyst',
 'anarchiccomedi',
 'ancient',
 'ancientrom',
 'ancientworld',
 'anderson',
 'andi',
 'andiemacdowel',
 'andrew',
 'android',
 'andy',
 'andygarcÃ­a',
 'angel',
 'angela',
 'angelabassett',
 'angeles',
 'angelinajoli',
 'anger',
 'angl',
 'angri',
 'ani',
 'anim',
 'animalattack',
 'animalhorror',
 'animals',
 'anjelicahuston',
 'ann',
 'anna',
 'annafari',
 'annakendrick',
 'anne',
 'annehathaway',
 'annemoss',
 'annetteben',
 'anni',
 'annie',
 'anniversari',
 'announc',
 'annual',
 'anonym',
 'anoth',
 'answer',
 'ant',
 'antholog',
 'anthoni',
 'anthonyanderson',
 'anthonyhopkin',
 'anthonymacki',
 'anthropomorph',
 'anti',
 'antic',
 'antihero',
 'antiqu',
 'antoinefuqua',
 'antoniobandera',
 'antonyelchin',
 'anyon',
 'anyth',
 'apart',
 'apartheid',
 'apartment',
 'ape',
 'apocalyp',
 'apocalypse',
 'apocalypt',
 'appar',
 'appear',
 'appl',
 'apple',
 'appoint',
 'appreci',
 'apprent',
 'approach',
 'april',
 'aquarium',
 'arab',
 'arch',
 'archaeologist',
 'archeolog',
 'archer',
 'architect',
 'arctic',
 'area',
 'aren',
 'arena',
 'argument',
 'ari',
 'aristocrat',
 'arm',
 'armi',
 'armor',
 'armsdeal',
 'army',
 'arnold',
 'arnoldschwarzenegg',
 'arrang',
 'arrangedmarriag',
 'arrest',
 'arriv',
 'arrog',
 'art',
 'arthur',
 'artifact',
 'artifici',
 'artificialintellig',
 'artist',
 'ash',
 'ashley',
 'ashleyjudd',
 'ashtonkutch',
 'asia',
 'asian',
 'asid',
 'ask',
 'aspect',
 'aspir',
 'assassin',
 'assault',
 'assembl',
 'assign',
 'assist',
 'assistant',
 'associ',
 'assum',
 'asteroid',
 'astronaut',
 'asylum',
 'atheist',
 'athlet',
 'atom',
 'atomicbomb',
 'attack',
 'attacks',
 'attempt',
 'attempttoescap',
 'attend',
 'attent',
 'attic',
 'attitud',
 'attorney',
 'attract',
 'auction',
 'audienc',
 'audit',
 'august',
 'aunt',
 'austin',
 'australia',
 'australian',
 'author',
 'autism',
 'auto',
 'automobilerac',
 'aveng',
 'averag',
 'avoid',
 'await',
 'awak',
 'awaken',
 'awar',
 'award',
 'away',
 'awkward',
 'awri',
 'awry',
 'ax',
 'ba',
 'babe',
 'babi',
 'baby',
 'bachelor',
 'backdrop',
 'background',
 'backpack',
 'bad',
 'bag',
 'bahama',
 'bail',
 'balanc',
 'ball',
 'ballet',
 'balloon',
 'baltimor',
 'ban',
 'band',
 'bandit',
 'bangkok',
 'banish',
 'bank',
 'banker',
 'bankrobb',
 'bankrobberi',
 'bar',
 'barbrastreisand',
 'bare',
 'bargain',
 'barn',
 'barney',
 'baron',
 'barri',
 'barrier',
 'barrylevinson',
 'barrysonnenfeld',
 'base',
 'baseb',
 'basedoncomicbook',
 'basedongraphicnovel',
 'basedonnovel',
 'basedonplay',
 'basedonstagemu',
 'basedontrueev',
 'basedontruestori',
 'basedontvseri',
 'basedonvideogam',
 'basedonyoungadultnovel',
 'basement',
 'basketb',
 'basketball',
 'bat',
 'batman',
 'battl',
 'battle',
 'battlefield',
 'bay',
 'beach',
 'beam',
 'bear',
 'beard',
 'beast',
 'beat',
 'beauti',
 'beautiful',
 'beautifulwoman',
 'beauty',
 'becam',
 'becau',
 'becki',
 'becom',
 'becominganadult',
 'bed',
 'bedroom',
 'bee',
 'beer',
 'befor',
 'befriend',
 'began',
 'begin',
 'begins',
 'behavior',
 'belief',
 'believ',
 'bell',
 'bella',
 'belong',
 'belov',
 'ben',
 'benaffleck',
 'bend',
 'beneath',
 'benefit',
 'benfost',
 'beniciodeltoro',
 'benjamin',
 'benjaminbratt',
 'benkingsley',
 'bennett',
 'benstil',
 'bent',
 'berlin',
 'best',
 'bestfriend',
 'bestfriendsinlov',
 'bet',
 'beth',
 'betray',
 'bettemidl',
 'better',
 'betti',
 'beverli',
 'bibl',
 'bid',
 'big',
 'bigger',
 'biggest',
 'bike',
 'biker',
 'bikini',
 'billhad',
 'billi',
 'billionair',
 'billmurray',
 'billnighi',
 'billpaxton',
 'billpullman',
 'billybobthornton',
 'billycrudup',
 'billycryst',
 'biographi',
 'biolog',
 'bird',
 'birth',
 'birthday',
 'bisexu',
 'bishop',
 'bit',
 'bite',
 'bitter',
 'bizarr',
 'black',
 'blackmag',
 'blackmail',
 'blackpeopl',
 'blade',
 'blame',
 'blend',
 'blind',
 'bliss',
 'blizzard',
 'block',
 'blond',
 'blood',
 'bloodi',
 'bloodsplatt',
 'bloodthirsti',
 'blow',
 'blue',
 'board',
 'boardingschool',
 'boat',
 'bob',
 'bobbi',
 'bobbyfarrelli',
 'bobhoskin',
 'bodi',
 'body',
 'bodyguard',
 'bold',
 'bollywood',
 'bomb',
 'bond',
 'bone',
 'book',
 'border',
 'bore',
 'boredom',
 'born',
 'boss',
 'boston',
 'botch',
 'bound',
 'boundari',
 'bounti',
 'bountyhunt',
 'bout',
 'box',
 'boxer',
 'boy',
 'boyfriend',
 'boys',
 'bradleycoop',
 'bradpitt',
 'brain',
 'brainwash',
 'brand',
 'brandon',
 'brave',
 'braveri',
 'brazil',
 'brazilian',
 'break',
 'breakdown',
 'breakup',
 'breast',
 'breath',
 'breed',
 'brendanfra',
 'brendangleeson',
 'brent',
 'brettratn',
 'brian',
 'briandepalma',
 'bride',
 'bridesmaid',
 'bridg',
 'brief',
 'brielarson',
 'brien',
 'bright',
 'brilliant',
 'bring',
 'brink',
 'britain',
 'british',
 'britishsecretserv',
 'brittanymurphi',
 'broadcast',
 'broadway',
 'broke',
 'broken',
 'broker',
 'bronx',
 'brook',
 'brooklyn',
 'broom',
 'brothel',
 'brother',
 'brotherbrotherrelationship',
 'brothers',
 'brothersisterrelationship',
 'brought',
 'brown',
 'bruce',
 'brucegreenwood',
 'brucewilli',
 'brutal',
 'bryans',
 'bu',
 'buck',
 'bud',
 'buddi',
 'buddy',
 'buddycomedi',
 'buddycop',
 'budget',
 'build',
 'building',
 'built',
 'bullet',
 'bulli',
 'bumbl',
 'bunch',
 'bunker',
 'bunni',
 'burglar',
 'buri',
 'burn',
 'bush',
 'busi',
 'business',
 'businessman',
 'bust',
 'butcher',
 'butler',
 'butt',
 'buy',
 'buzz',
 'cabin',
 'caesar',
 'cage',
 'cairo',
 'cal',
 'california',
 'calvin',
 'camcord',
 'came',
 'camera',
 'cameraman',
 'camerondiaz',
 'camp',
 'campaign',
 'campbell',
 'campu',
 'canada',
 'canadian',
 'cancer',
 'candi',
 'candid',
 'canin',
 'cannib',
 'canuxploit',
 'capabl',
 'caper',
 'capit',
 'capt',
 'captain',
 'captiv',
 'captur',
 'capture',
 'car',
 'caraccid',
 'carcha',
 'carcrash',
 'card',
 'care',
 'career',
 'carefr',
 'caretak',
 'careymulligan',
 'caribbean',
 'carjourney',
 'carl',
 'carlagugino',
 'carmen',
 'carol',
 'carolina',
 'carrac',
 'carri',
 'carrie',
 'cartel',
 'carter',
 'cartoon',
 'caryelw',
 'case',
 'caseyaffleck',
 'cash',
 'casino',
 'cast',
 'castl',
 'cat',
 'cataclysm',
 'catastroph',
 'catch',
 'cateblanchett',
 'catherinedeneuv',
 'catherinekeen',
 'catherinezeta',
 'cathol',
 'cattl',
 'cau',
 'caught',
 'cavalri',
 'cave',
 'cavemen',
 'celebr',
 'celebration',
 'cell',
 'cellphon',
 'cemeteri',
 'center',
 'centr',
 'central',
 'centuri',
 'centuries',
 'century',
 'ceo',
 'certain',
 'chad',
 'chain',
 'chainsaw',
 'challeng',
 'chamber',
 'champion',
 'championship',
 'chanc',
 'chance',
 'chang',
 'change',
 'changed',
 'changes',
 'channingtatum',
 'chao',
 'chaos',
 'chaotic',
 'chapter',
 'charact',
 'character',
 'characters',
 'charg',
 'charismat',
 'charl',
 'charli',
 'charlie',
 'charliesheen',
 'charlizetheron',
 'charm',
 'chart',
 'chase',
 'chauffeur',
 'chazzpalminteri',
 'cheat',
 'check',
 'cheerlead',
 'chef',
 'chemic',
 'cher',
 'chevycha',
 'chicago',
 'chicken',
 'chief',
 'child',
 'childabu',
 'childhero',
 'childhood',
 'childprodigi',
 'children',
 'chill',
 'chimp',
 'china',
 'chine',
 'chip',
 'chipmunk',
 'chiwetelejiofor',
 'chloe',
 'chloÃ«gracemoretz',
 'chloÃ«sevigni',
 'chocol',
 'choic',
 'choice',
 'choo',
 'chosen',
 'chowyun',
 'chri',
 'chriscolumbu',
 'chriscoop',
 'chrisevan',
 'chrishemsworth',
 'chrisklein',
 'chrispin',
 'chrisrock',
 'christ',
 'christian',
 'christianb',
 'christianslat',
 'christin',
 'christinaappleg',
 'christinaricci',
 'christma',
 'christmas',
 'christmasparti',
 'christmastr',
 'christoph',
 'christopherlambert',
 'christopherlloyd',
 'christophernolan',
 'christopherplumm',
 'christopherwalken',
 'christophwaltz',
 'chrisweitz',
 'chronicl',
 'chuck',
 'church',
 'cia',
 'ciarÃ¡nhind',
 'cigarettesmok',
 'cillianmurphi',
 'cinema',
 'circl',
 'circu',
 'circuit',
 'circumst',
 'citi',
 'citizen',
 'city',
 'civil',
 'civilian',
 'civilwar',
 'claim',
 'clair',
 'clairedan',
 'claireforlani',
 'clan',
 'clark',
 'clash',
 'class',
 'classdiff',
 'classic',
 'classmat',
 'classroom',
 'claudevandamm',
 'clay',
 'clean',
 'clear',
 'clerk',
 'clever',
 'client',
 'clients',
 'cliff',
 'climat',
 'climb',
 'clinteastwood',
 'cliveowen',
 'clock',
 'clone',
 'close',
 'closer',
 'cloud',
 'clown',
 'club',
 'clue',
 'clueless',
 'clutch',
 'coach',
 'coast',
 'cocain',
 'code',
 'coffin',
 'cohen',
 'col',
 'cold',
 'coldwar',
 'cole',
 'colin',
 'colinfarrel',
 'colinfirth',
 'collap',
 'colleagu',
 'collect',
 'collector',
 'colleg',
 'college',
 'colli',
 'collid',
 'colombia',
 'colonel',
 'coloni',
 'color',
 'colorado',
 'coma',
 'combat',
 'combin',
 'come',
 'comeback',
 'comedi',
 'comedian',
 'comedy',
 'comet',
 'comfort',
 'comic',
 'coming',
 'comingofag',
 'comingout',
 'command',
 'commando',
 'commerci',
 'commiss',
 'commit',
 'common',
 'commun',
 'communist',
 'community',
 'compani',
 'companion',
 'company',
 'compass',
 'compet',
 'competit',
 'competition',
 'complet',
 'complex',
 'complic',
 'compo',
 'compul',
 'comput',
 'computerviru',
 'conan',
 'concern',
 'concert',
 'concoct',
 'condit',
 'conduct',
 'confed',
 'confess',
 'confid',
 'confin',
 'conflict',
 'confront',
 'confu',
 'congress',
 'conman',
 'connect',
 'connecticut',
 'connel',
 'connor',
 'conquer',
 'consequ',
 'consequences',
 'conserv',
 'consid',
 'conspir',
 'conspiraci',
 'conspiracy',
 'constant',
 'constantli',
 'construct',
 'consum',
 'contact',
 'contain',
 'contemporari',
 'contend',
 'content',
 'contest',
 'contin',
 'continu',
 'contract',
 'contractor',
 'control',
 'controversi',
 'convent',
 'conver',
 'converg',
 'convict',
 'convinc',
 ...]

In [742]:
from sklearn.metrics.pairwise import cosine_similarity

In [743]:
similarity = cosine_similarity(vectors)

In [759]:
#sorting on the basis of the second number that is similarities

sorted(list(enumerate(similarity[2])), reverse=True, key=lambda x:x[1])

[(2, 0.9999999999999999),
 (11, 0.3609974361905776),
 (29, 0.3307189138830738),
 (1346, 0.32639560491693337),
 (4077, 0.2611164839335467),
 (1749, 0.2390457218668787),
 (3340, 0.22941573387056174),
 (3166, 0.22645540682891913),
 (1723, 0.22613350843332267),
 (1134, 0.22225022225033336),
 (4343, 0.220630652030457),
 (147, 0.21221867190679128),
 (166, 0.19094065395649332),
 (3255, 0.18446619684315546),
 (3289, 0.18042195912175807),
 (1103, 0.1796053020267749),
 (227, 0.17928429140015903),
 (4641, 0.17677669529663687),
 (277, 0.1735912687073534),
 (1203, 0.171601618245911),
 (4010, 0.17149858514250882),
 (1719, 0.16984155512168936),
 (1087, 0.16839382851364085),
 (1843, 0.1670382761952652),
 (218, 0.16666666666666666),
 (972, 0.16413304107465318),
 (170, 0.16248342090492035),
 (108, 0.15811388300841897),
 (3355, 0.15811388300841897),
 (2925, 0.15811388300841894),
 (3975, 0.1543033499620919),
 (973, 0.15386436372416593),
 (4697, 0.15309310892394862),
 (17, 0.15231794896123557),
 (46, 0.15158476564770806),
 (105, 0.1507556722888818),
 (2753, 0.1507556722888818),
 (1775, 0.15006126199969522),
 (2169, 0.1494035761667992),
 (3347, 0.1494035761667992),
 (1194, 0.14744195615489714),
 (3498, 0.14731391274719738),
 (58, 0.147087101353638),
 (282, 0.147087101353638),
 (2675, 0.147087101353638),
 (1237, 0.1453095484297741),
 (695, 0.14433756729740646),
 (1085, 0.14433756729740646),
 (1080, 0.1433848336691011),
 (2680, 0.14301938838683884),
 (698, 0.1417366773784602),
 (3622, 0.14153462926807447),
 (134, 0.1414213562373095),
 (2364, 0.13927150363278887),
 (508, 0.13803940759355818),
 (62, 0.1369306393762915),
 (1369, 0.13638618139749523),
 (939, 0.13582634199860824),
 (2395, 0.134790966504298),
 (2652, 0.13363062095621217),
 (3770, 0.13363062095621217),
 (7, 0.1332504477222565),
 (2056, 0.1332504477222565),
 (2332, 0.13258252147247765),
 (88, 0.13130643285972254),
 (356, 0.13130643285972254),
 (1004, 0.13130643285972254),
 (3356, 0.13130643285972254),
 (1938, 0.13032150878567172),
 (1027, 0.12909944487358055),
 (372, 0.12892765578234916),
 (3721, 0.12862393885688161),
 (3263, 0.1270001270001905),
 (129, 0.12626906806902632),
 (596, 0.12626906806902632),
 (1537, 0.12626906806902632),
 (1592, 0.125),
 (1621, 0.125),
 (23, 0.12499999999999997),
 (294, 0.12499999999999997),
 (1703, 0.12499999999999997),
 (50, 0.12309149097933274),
 (2496, 0.12309149097933274),
 (4406, 0.12309149097933274),
 (1445, 0.12257258446136501),
 (3147, 0.12247448713915887),
 (205, 0.12166606584807188),
 (256, 0.12166606584807188),
 (808, 0.12166606584807188),
 (1284, 0.12166606584807188),
 (3730, 0.12166606584807188),
 (2080, 0.12141073279465801),
 (152, 0.12126781251816646),
 (180, 0.12028130608117202),
 (1676, 0.12028130608117202),
 (2301, 0.11962753722931604),
 (3428, 0.11952286093343936),
 (753, 0.11952286093343935),
 (859, 0.11952286093343935),
 (1513, 0.11952286093343935),
 (3140, 0.11952286093343935),
 (2404, 0.11918282365569903),
 (466, 0.11858541225631421),
 (2297, 0.11858541225631421),
 (3863, 0.11858541225631421),
 (2052, 0.1181138978153835),
 (245, 0.1178511301977579),
 (229, 0.11713032141645455),
 (164, 0.11624763874381927),
 (332, 0.11624763874381927),
 (2683, 0.11624763874381927),
 (418, 0.11572751247156893),
 (1670, 0.11572751247156893),
 (2999, 0.11572751247156893),
 (190, 0.11507182723729042),
 (1305, 0.11507182723729042),
 (241, 0.11470786693528087),
 (329, 0.11470786693528087),
 (1178, 0.11470786693528087),
 (1921, 0.11470786693528087),
 (1463, 0.11410886614690958),
 (2760, 0.11410886614690958),
 (174, 0.11322770341445956),
 (437, 0.11322770341445956),
 (687, 0.11322770341445956),
 (711, 0.11322770341445956),
 (654, 0.11316968255314816),
 (56, 0.11306675421666135),
 (249, 0.11306675421666135),
 (2558, 0.11306675421666135),
 (3055, 0.11306675421666133),
 (1396, 0.11225331376673431),
 (26, 0.11180339887498948),
 (207, 0.11180339887498948),
 (1086, 0.11180339887498948),
 (2750, 0.11180339887498948),
 (3025, 0.11180339887498948),
 (3152, 0.11180339887498948),
 (187, 0.11180339887498947),
 (151, 0.11058146711617285),
 (367, 0.11058146711617285),
 (498, 0.11058146711617285),
 (1886, 0.11058146711617285),
 (38, 0.11048543456039804),
 (252, 0.11048543456039804),
 (370, 0.11043152607484653),
 (952, 0.11043152607484653),
 (1380, 0.11043152607484653),
 (160, 0.1093987436234209),
 (210, 0.10910894511799618),
 (677, 0.10910894511799618),
 (988, 0.10910894511799618),
 (139, 0.10879853497231112),
 (267, 0.10825317547305485),
 (1154, 0.10825317547305485),
 (2250, 0.10825317547305485),
 (2549, 0.10798355319767),
 (708, 0.10783277320343841),
 (2008, 0.10783277320343841),
 (3675, 0.10783277320343841),
 (36, 0.10660035817780521),
 (350, 0.10660035817780521),
 (1367, 0.10660035817780521),
 (1401, 0.10660035817780521),
 (3184, 0.10660035817780521),
 (3595, 0.10660035817780521),
 (3614, 0.10660035817780521),
 (3888, 0.10660035817780521),
 (4148, 0.10660035817780521),
 (263, 0.10606601717798213),
 (721, 0.10606601717798213),
 (783, 0.10606601717798213),
 (1727, 0.10606601717798213),
 (2762, 0.10606601717798213),
 (2919, 0.10606601717798213),
 (4472, 0.10606601717798213),
 (4623, 0.10606601717798213),
 (9, 0.10540925533894598),
 (580, 0.10540925533894598),
 (683, 0.10540925533894598),
 (1297, 0.10540925533894598),
 (76, 0.10425720702853737),
 (371, 0.10425720702853737),
 (1648, 0.10425720702853737),
 (3235, 0.10425720702853737),
 (325, 0.10400628679223047),
 (751, 0.10400628679223047),
 (773, 0.10400628679223047),
 (1076, 0.10400628679223047),
 (1365, 0.10400628679223047),
 (4509, 0.10400628679223047),
 (2005, 0.103450736075296),
 (2086, 0.103450736075296),
 (4048, 0.103450736075296),
 (724, 0.10314212462587934),
 (831, 0.10314212462587934),
 (94, 0.10206207261596575),
 (483, 0.10206207261596575),
 (1096, 0.10206207261596575),
 (1276, 0.10206207261596575),
 (1617, 0.10206207261596575),
 (1721, 0.10206207261596575),
 (2007, 0.10206207261596575),
 (2095, 0.10206207261596575),
 (2283, 0.10206207261596575),
 (2650, 0.10206207261596575),
 (3229, 0.10206207261596575),
 (3720, 0.10206207261596575),
 (4405, 0.10206207261596575),
 (4502, 0.10206207261596575),
 (307, 0.10159281922178943),
 (531, 0.10101525445522105),
 (3407, 0.10101525445522105),
 (4015, 0.10067340828210364),
 (219, 0.10022296571715913),
 (1425, 0.10022296571715913),
 (3046, 0.10022296571715913),
 (3438, 0.10022296571715913),
 (1574, 0.10008009612817945),
 (1583, 0.09999999999999999),
 (167, 0.09847982464479191),
 (400, 0.09847982464479191),
 (590, 0.09847982464479191),
 (781, 0.09847982464479191),
 (1092, 0.09847982464479191),
 (3557, 0.09847982464479191),
 (248, 0.09805806756909201),
 (3363, 0.09805806756909201),
 (4348, 0.09805806756909201),
 (4419, 0.09805806756909201),
 (3212, 0.09752368720068673),
 (1250, 0.09712858623572641),
 (2162, 0.09712858623572641),
 (292, 0.09682458365518541),
 (1079, 0.09682458365518541),
 (1364, 0.09682458365518541),
 (1833, 0.09682458365518541),
 (2062, 0.09682458365518541),
 (2741, 0.09682458365518541),
 (3264, 0.09682458365518541),
 (3322, 0.09682458365518541),
 (4683, 0.09682458365518541),
 (188, 0.09622504486493762),
 (1432, 0.09622504486493762),
 (183, 0.0958706236059213),
 (386, 0.09534625892455922),
 (2448, 0.0953116064578779),
 (260, 0.09525009525014289),
 (794, 0.09525009525014289),
 (960, 0.09525009525014289),
 (1259, 0.09525009525014289),
 (2202, 0.09525009525014289),
 (3890, 0.09525009525014289),
 (4781, 0.09525009525014289),
 (119, 0.0944911182523068),
 (314, 0.0944911182523068),
 (354, 0.0944911182523068),
 (3854, 0.0944911182523068),
 (3949, 0.0944911182523068),
 (3000, 0.09422229518055111),
 (121, 0.09374999999999999),
 (28, 0.09374999999999997),
 (457, 0.09374999999999997),
 (678, 0.09374999999999997),
 (840, 0.09374999999999997),
 (1301, 0.09374999999999997),
 (1431, 0.09374999999999997),
 (2261, 0.09374999999999997),
 (2400, 0.09374999999999997),
 (2354, 0.09365858115816939),
 (425, 0.09284766908852592),
 (696, 0.09284766908852592),
 (3731, 0.09284766908852592),
 (577, 0.09231861823449955),
 (1142, 0.09231861823449955),
 (1616, 0.09231861823449955),
 (1667, 0.09231861823449955),
 (2280, 0.09231861823449955),
 (2937, 0.09231861823449955),
 (4770, 0.09231861823449955),
 (4775, 0.09231861823449955),
 (750, 0.09205746178983235),
 (4432, 0.09205746178983235),
 (534, 0.09128709291752767),
 (1879, 0.09128709291752767),
 (2153, 0.09128709291752767),
 (2480, 0.09128709291752767),
 (3978, 0.09128709291752767),
 (468, 0.09095085938862485),
 (544, 0.09095085938862485),
 (579, 0.09095085938862485),
 (741, 0.09095085938862485),
 (2206, 0.09095085938862485),
 (4468, 0.09095085938862485),
 (1751, 0.09053574604251853),
 (2439, 0.09053574604251853),
 (1634, 0.08974476982721727),
 (67, 0.08964214570007951),
 (512, 0.08964214570007951),
 (987, 0.08964214570007951),
 (1821, 0.08964214570007951),
 (1842, 0.08964214570007951),
 (2929, 0.08964214570007951),
 (3301, 0.08964214570007951),
 (63, 0.08908708063747478),
 (1366, 0.08908708063747478),
 (1878, 0.08908708063747478),
 (2106, 0.08908708063747478),
 (4488, 0.08908708063747478),
 (72, 0.08838834764831843),
 (866, 0.08838834764831843),
 (901, 0.08838834764831843),
 (1041, 0.08838834764831843),
 (1199, 0.08838834764831843),
 (1444, 0.08838834764831843),
 (1585, 0.08838834764831843),
 (1798, 0.08838834764831843),
 (2061, 0.08838834764831843),
 (2789, 0.08838834764831843),
 (2865, 0.08838834764831843),
 (3236, 0.08838834764831843),
 (3496, 0.08838834764831843),
 (3527, 0.08838834764831843),
 (3602, 0.08838834764831843),
 (3733, 0.08838834764831843),
 (4568, 0.08838834764831843),
 (2173, 0.08770580193070292),
 (2752, 0.08770580193070292),
 (889, 0.08751750525175062),
 (0, 0.08718572905786445),
 (126, 0.08718572905786445),
 (1485, 0.08718572905786445),
 (1739, 0.08718572905786445),
 (1746, 0.08718572905786445),
 (1758, 0.08718572905786445),
 (3295, 0.08718572905786445),
 (51, 0.086386842558136),
 (1898, 0.086386842558136),
 (131, 0.08603090020146065),
 (1454, 0.08603090020146065),
 (1548, 0.08603090020146065),
 (2072, 0.08603090020146065),
 (2419, 0.08603090020146065),
 (4078, 0.08603090020146065),
 (47, 0.08574929257125441),
 (153, 0.08574929257125441),
 (186, 0.08574929257125441),
 (1360, 0.08574929257125441),
 (1437, 0.08574929257125441),
 (1464, 0.08574929257125441),
 (1673, 0.08574929257125441),
 (1926, 0.08574929257125441),
 (2780, 0.08574929257125441),
 (3832, 0.08574929257125441),
 (4261, 0.08574929257125441),
 (4796, 0.08574929257125441),
 (223, 0.08492077756084468),
 (402, 0.08492077756084468),
 (731, 0.08492077756084468),
 (1015, 0.08492077756084468),
 (1113, 0.08492077756084468),
 (1195, 0.08492077756084468),
 (1900, 0.08492077756084468),
 (2211, 0.08492077756084468),
 (2817, 0.08492077756084468),
 (589, 0.08451542547285165),
 (10, 0.08385254915624211),
 (40, 0.08385254915624211),
 (138, 0.08385254915624211),
 (844, 0.08385254915624211),
 (2686, 0.08385254915624211),
 (274, 0.0838525491562421),
 (310, 0.0835191380976326),
 (739, 0.08333333333333333),
 (1104, 0.08333333333333333),
 (1139, 0.08333333333333333),
 (1613, 0.08333333333333333),
 (3081, 0.08333333333333333),
 (3918, 0.08333333333333333),
 (78, 0.0828236445561349),
 (163, 0.0828236445561349),
 (369, 0.0828236445561349),
 (659, 0.0828236445561349),
 (1511, 0.0828236445561349),
 (1523, 0.0828236445561349),
 (1602, 0.0828236445561349),
 (2247, 0.0828236445561349),
 (2377, 0.0828236445561349),
 (2823, 0.0828236445561349),
 (2916, 0.0828236445561349),
 (3401, 0.0828236445561349),
 (3697, 0.0828236445561349),
 (18, 0.0827605888602368),
 (755, 0.0827605888602368),
 (4711, 0.08219949365267865),
 (168, 0.08183170883849714),
 (330, 0.08183170883849714),
 (503, 0.08183170883849714),
 (680, 0.08183170883849714),
 (1913, 0.08183170883849714),
 (2160, 0.08183170883849714),
 (2180, 0.08183170883849714),
 (2450, 0.08183170883849714),
 (2984, 0.08183170883849714),
 (3169, 0.08183170883849714),
 (4045, 0.08183170883849714),
 (800, 0.08111071056538126),
 (914, 0.08111071056538126),
 (995, 0.08111071056538126),
 (1026, 0.08111071056538126),
 (1323, 0.08111071056538126),
 (2274, 0.08111071056538126),
 (2335, 0.08111071056538126),
 (2539, 0.08111071056538126),
 (2935, 0.08111071056538126),
 (3077, 0.08111071056538126),
 (3243, 0.08111071056538126),
 (3303, 0.08111071056538126),
 (4066, 0.08111071056538126),
 (4131, 0.08111071056538126),
 (4412, 0.08111071056538126),
 (291, 0.0808745799025788),
 (394, 0.0808745799025788),
 (594, 0.0808745799025788),
 (2934, 0.0808745799025788),
 (3620, 0.0808745799025788),
 (3481, 0.08058229640253801),
 (339, 0.0799502686333539),
 (514, 0.0799502686333539),
 (557, 0.0799502686333539),
 (958, 0.0799502686333539),
 (968, 0.0799502686333539),
 (1109, 0.0799502686333539),
 (1204, 0.0799502686333539),
 (1299, 0.0799502686333539),
 (1471, 0.0799502686333539),
 (1823, 0.0799502686333539),
 (1912, 0.0799502686333539),
 (2352, 0.0799502686333539),
 (3805, 0.0799502686333539),
 (3845, 0.0799502686333539),
 (127, 0.07955572841757301),
 (261, 0.07905694150420949),
 (523, 0.07905694150420949),
 (629, 0.07905694150420949),
 (833, 0.07905694150420949),
 (930, 0.07905694150420949),
 (944, 0.07905694150420949),
 (2014, 0.07905694150420949),
 (3855, 0.07905694150420949),
 (4334, 0.07905694150420949),
 (4531, 0.07905694150420949),
 (179, 0.07905694150420947),
 (200, 0.07905694150420947),
 (613, 0.07905694150420947),
 (627, 0.07905694150420947),
 (858, 0.07905694150420947),
 (924, 0.07905694150420947),
 (1789, 0.07905694150420947),
 (2394, 0.07905694150420947),
 (3141, 0.07905694150420947),
 (3627, 0.07905694150420947),
 (3972, 0.07905694150420947),
 (4162, 0.07905694150420947),
 (4425, 0.07905694150420947),
 (1106, 0.07856742013183861),
 (1456, 0.07856742013183861),
 (412, 0.07819290527140303),
 (872, 0.07819290527140303),
 (1061, 0.07819290527140303),
 (1205, 0.07819290527140303),
 (1831, 0.07819290527140303),
 (2341, 0.07819290527140303),
 (2885, 0.07819290527140303),
 (4083, 0.07819290527140303),
 (426, 0.07808688094430302),
 (1541, 0.07808688094430302),
 (1641, 0.07808688094430302),
 (3739, 0.07808688094430302),
 (4082, 0.07808688094430302),
 (2790, 0.07761505257063328),
 (4, 0.0773565934694095),
 (41, 0.0773565934694095),
 (543, 0.0773565934694095),
 (587, 0.0773565934694095),
 (870, 0.0773565934694095),
 (1273, 0.0773565934694095),
 (2897, 0.0773565934694095),
 (3039, 0.0773565934694095),
 (3704, 0.0773565934694095),
 (490, 0.07715167498104596),
 (653, 0.07715167498104596),
 (1166, 0.07715167498104596),
 (1410, 0.07715167498104596),
 (1476, 0.07715167498104596),
 (2385, 0.07715167498104596),
 (2656, 0.07715167498104596),
 (2962, 0.07715167498104596),
 (2980, 0.07715167498104596),
 (3004, 0.07715167498104596),
 (3420, 0.07715167498104596),
 (4135, 0.07715167498104596),
 (4231, 0.07715167498104596),
 (4354, 0.07715167498104596),
 (4783, 0.07715167498104596),
 (182, 0.07654655446197431),
 (444, 0.07654655446197431),
 (574, 0.07654655446197431),
 (767, 0.07654655446197431),
 (788, 0.07654655446197431),
 (1140, 0.07654655446197431),
 (1692, 0.07654655446197431),
 (2328, 0.07654655446197431),
 (4795, 0.07654655446197431),
 (97, 0.07576144084141578),
 (243, 0.07576144084141578),
 (782, 0.07576144084141578),
 (1446, 0.07576144084141578),
 (233, 0.0753778361444409),
 (657, 0.0753778361444409),
 (1327, 0.0753778361444409),
 (1681, 0.0753778361444409),
 (2323, 0.0753778361444409),
 (2521, 0.0753778361444409),
 (3352, 0.0753778361444409),
 (3621, 0.0753778361444409),
 (3839, 0.0753778361444409),
 (4290, 0.0753778361444409),
 (4303, 0.0753778361444409),
 (419, 0.075),
 (611, 0.075),
 (1003, 0.075),
 (1220, 0.075),
 (1285, 0.075),
 (2243, 0.075),
 (4098, 0.075),
 (600, 0.07426106572325056),
 (665, 0.07426106572325056),
 (758, 0.07426106572325056),
 (1127, 0.07426106572325056),
 (1418, 0.07426106572325056),
 (3310, 0.07426106572325056),
 (4538, 0.07426106572325056),
 (209, 0.07372097807744857),
 (308, 0.07372097807744857),
 (476, 0.07372097807744857),
 (505, 0.07372097807744857),
 (1152, 0.07372097807744857),
 (1226, 0.07372097807744857),
 (1544, 0.07372097807744857),
 (1860, 0.07372097807744857),
 (2117, 0.07372097807744857),
 (3086, 0.07372097807744857),
 (3395, 0.07372097807744857),
 (3590, 0.07372097807744857),
 (3663, 0.07372097807744857),
 (3678, 0.07372097807744857),
 (3898, 0.07372097807744857),
 (3982, 0.07372097807744857),
 (4216, 0.07372097807744857),
 (4285, 0.07372097807744857),
 (4593, 0.07372097807744857),
 (140, 0.073543550676819),
 (702, 0.073543550676819),
 (1435, 0.073543550676819),
 (1748, 0.073543550676819),
 (3341, 0.073543550676819),
 (3389, 0.073543550676819),
 (3414, 0.073543550676819),
 (30, 0.07284643967679481),
 (83, 0.07284643967679481),
 (123, 0.07284643967679481),
 (158, 0.07284643967679481),
 (582, 0.07284643967679481),
 (735, 0.07284643967679481),
 (777, 0.07284643967679481),
 (2351, 0.07284643967679481),
 (2411, 0.07284643967679481),
 (3508, 0.07284643967679481),
 (35, 0.07216878364870323),
 (61, 0.07216878364870323),
 (157, 0.07216878364870323),
 (162, 0.07216878364870323),
 (201, 0.07216878364870323),
 (237, 0.07216878364870323),
 (604, 0.07216878364870323),
 (715, 0.07216878364870323),
 (1055, 0.07216878364870323),
 (1077, 0.07216878364870323),
 (1494, 0.07216878364870323),
 (2078, 0.07216878364870323),
 (2244, 0.07216878364870323),
 (2378, 0.07216878364870323),
 (2584, 0.07216878364870323),
 (2622, 0.07216878364870323),
 (3467, 0.07216878364870323),
 (215, 0.07216878364870322),
 (228, 0.07216878364870322),
 (270, 0.07216878364870322),
 (645, 0.07216878364870322),
 (1112, 0.07216878364870322),
 (4694, 0.07216878364870322),
 (304, 0.07169241683455055),
 (396, 0.07150969419341942),
 (694, 0.07150969419341942),
 (1650, 0.07150969419341942),
 (1958, 0.07150969419341942),
 (2133, 0.07150969419341942),
 (2135, 0.07150969419341942),
 (3458, 0.0708683386892301),
 (5, 0.07086833868923009),
 (33, 0.07071067811865475),
 (109, 0.07071067811865475),
 (216, 0.07071067811865475),
 (368, 0.07071067811865475),
 (1438, 0.07071067811865475),
 (1486, 0.07071067811865475),
 (1562, 0.07071067811865475),
 (1787, 0.07071067811865475),
 (2067, 0.07071067811865475),
 (2231, 0.07071067811865475),
 (2310, 0.07071067811865475),
 (2579, 0.07071067811865475),
 (2882, 0.07071067811865475),
 (3336, 0.07071067811865475),
 (3374, 0.07071067811865475),
 (3558, 0.07071067811865475),
 (3856, 0.07071067811865475),
 (4476, 0.07071067811865475),
 (985, 0.07035975447302918),
 (746, 0.07024393586862704),
 (1155, 0.07024393586862704),
 (2142, 0.06967330142916177),
 (262, 0.06963575181639443),
 (507, 0.06963575181639443),
 (1733, 0.06963575181639443),
 (2527, 0.06963575181639443),
 (31, 0.06933752452815364),
 (487, 0.06933752452815364),
 (495, 0.06933752452815364),
 (561, 0.06933752452815364),
 (791, 0.06933752452815364),
 (1044, 0.06933752452815364),
 (1423, 0.06933752452815364),
 (1854, 0.06933752452815364),
 (2228, 0.06933752452815364),
 (2463, 0.06933752452815364),
 (2508, 0.06933752452815364),
 (2564, 0.06933752452815364),
 (3133, 0.06933752452815364),
 (3148, 0.06933752452815364),
 (3421, 0.06933752452815364),
 (3593, 0.06933752452815364),
 (3857, 0.06933752452815364),
 (3911, 0.06933752452815364),
 (4297, 0.06933752452815364),
 (4355, 0.06933752452815364),
 (4433, 0.06933752452815364),
 (48, 0.06904309634237427),
 (273, 0.06904309634237427),
 (305, 0.06904309634237427),
 (1281, 0.06904309634237427),
 (1462, 0.06904309634237427),
 (1496, 0.06904309634237427),
 (3740, 0.06904309634237427),
 (4647, 0.06904309634237427),
 (15, 0.06846531968814575),
 (19, 0.06846531968814575),
 (253, 0.06846531968814575),
 (591, 0.06846531968814575),
 (873, 0.06846531968814575),
 (1122, 0.06846531968814575),
 (2498, 0.06846531968814575),
 (3607, 0.06846531968814575),
 (202, 0.06804138174397717),
 (290, 0.06804138174397717),
 (433, 0.06804138174397717),
 (660, 0.06804138174397717),
 (920, 0.06804138174397717),
 (1049, 0.06804138174397717),
 (1158, 0.06804138174397717),
 (1391, 0.06804138174397717),
 (1686, 0.06804138174397717),
 (1943, 0.06804138174397717),
 (2342, 0.06804138174397717),

In [836]:
#Main Recommendation Section

def recommend(movie):
    movie_index = new_df[new_df['title'] == movie].index[0]
    distances = similarity[movie_index]
             #sorting the list-  Similarity between movies- sort by second value not index- show 5 similar movies              
    movies_list = sorted(list(enumerate(distances)),reverse=True,key=lambda x:x[1])[1:6]
    
    for i in movies_list:
        print(new_df.iloc[i[0]].title)
#         print(i[0])
    return

In [837]:
recommend('The Avengers')

Iron Man 3
Avengers: Age of Ultron
Captain America: Civil War
Captain America: The First Avenger
Iron Man

In [838]:
print(new_df.iloc[1216])

movie_id                                                  440
title                             Aliens vs Predator: Requiem
tags        a sequel to 2004' alien vs. predator, the icon...
Name: 1216, dtype: object

In [839]:
new_df[new_df['title'] == "Batman"].index[0]

1362

In [840]:
#Temporary Output

# recommend('Spider-Man') 
recommend('Batman')
# recommend('Men in Black')

Spider-Man 3
Spider-Man 2
The Amazing Spider-Man 2
Arachnophobia
The Amazing Spider-Man
Batman
Batman & Robin
Batman Begins
Batman Returns
The R.M.
Men in Black II
Men in Black 3
Meet Dave
Independence Daysaster
Impostor